### ISSUE TITLE
Handle folders that doesn't exist 

### ISSUE THREAD

**Issue by stofolus** [stofolus/pnr-scanner#28]
If a folder or file is specified but doesn't exist we get a crash and a stacktrace.

```
bin/bin.js asdda
fs.js:961
  binding.lstat(pathModule.toNamespacedPath(path));
          ^

Error: ENOENT: no such file or directory, lstat '/Users/stoffe/Development/pnr-scanner/asdda'
    at Object.fs.lstatSync (fs.js:961:11)
    at Function.findPnrs (/Users/stoffe/Development/pnr-scanner/lib/finder.js:15:12)
    at Object.<anonymous> (/Users/stoffe/Development/pnr-scanner/bin/bin.js:29:33)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
```

**Comment by stofolus** [comment]
Fixed
